const STORAGE_KEY='ledgerly-trades-v1';
let trades=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
let sort={key:'date',dir:'desc'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n||0);
const dateFmt=v=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v));
const pnl=t=>((t.side==='long'?t.exitPrice-t.entryPrice:t.entryPrice-t.exitPrice)*t.quantity);
const pnlPct=t=>pnl(t)/(t.entryPrice*t.quantity)*100;
const hold=t=>{const m=Math.max(0,(new Date(t.exitDate)-new Date(t.entryDate))/60000);if(m<60)return `${Math.round(m)}m`;if(m<1440)return `${(m/60).toFixed(m%60?1:0)}h`;return `${(m/1440).toFixed(1)}d`};
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(trades))}
function signed(v){return `${v>0?'+':''}${money(v)}`}
function setPnl(el,v){el.textContent=signed(v);el.className=v>0?'positive':v<0?'negative':''}
function updateDashboard(){
 const n=trades.length,wins=trades.filter(t=>pnl(t)>0),losses=trades.filter(t=>pnl(t)<0),total=trades.reduce((s,t)=>s+pnl(t),0),avgWin=wins.length?wins.reduce((s,t)=>s+pnl(t),0)/wins.length:0,avgLoss=losses.length?losses.reduce((s,t)=>s+pnl(t),0)/losses.length:0;
 setPnl($('#netPnl'),total);$('#pnlContext').textContent=n?`${n} closed trade${n===1?'':'s'} logged`:'Start logging trades to see progress';$('#winRate').textContent=n?`${Math.round(wins.length/n*100)}%`:'—';$('#winContext').textContent=n?`${wins.length} win${wins.length===1?'':'s'} / ${losses.length} loss${losses.length===1?'':'es'}`:'No closed trades yet';$('#avgWinLoss').textContent=wins.length||losses.length?`${money(avgWin)} / ${money(Math.abs(avgLoss))}`:'—';$('#avgContext').textContent=wins.length&&losses.length?`Reward ${Math.abs(avgWin/avgLoss).toFixed(2)}× your risk`:'Risk reward will appear here';$('#tradeCount').textContent=n;$('#tradeContext').textContent=n?'Keep building your data set':'Your journal is ready';
 const ordered=[...trades].sort((a,b)=>new Date(a.exitDate)-new Date(b.exitDate));const best=ordered.length?[...ordered].sort((a,b)=>pnl(b)-pnl(a))[0]:null,worst=ordered.length?[...ordered].sort((a,b)=>pnl(a)-pnl(b))[0]:null;$('#bestTrade').textContent=best?`${best.symbol} · ${signed(pnl(best))}`:'—';$('#worstTrade').textContent=worst?`${worst.symbol} · ${signed(pnl(worst))}`:'—';$('#avgHold').textContent=n?hold({entryDate:0,exitDate:trades.reduce((s,t)=>s+(new Date(t.exitDate)-new Date(t.entryDate)),0)/n}):'—';const grossProfit=wins.reduce((s,t)=>s+pnl(t),0),grossLoss=Math.abs(losses.reduce((s,t)=>s+pnl(t),0));$('#profitFactor').textContent=grossLoss?(grossProfit/grossLoss).toFixed(2):grossProfit?'∞':'—';drawChart(ordered);renderTags();renderRecent();
}
function drawChart(items){const svg=$('#equityChart'),empty=$('#chartEmpty');svg.innerHTML='';if(!items.length){empty.classList.remove('hidden');return}empty.classList.add('hidden');let value=0,points=items.map(t=>(value+=pnl(t)));const min=Math.min(0,...points),max=Math.max(0,...points),range=max-min||1;const xy=points.map((v,i)=>[i/(Math.max(points.length-1,1))*650+25,220-(v-min)/range*175+5]);for(let i=0;i<4;i++){const y=20+i*60;svg.innerHTML+=`<line x1="25" y1="${y}" x2="675" y2="${y}" stroke="#263047" stroke-width="1"/>`}const coords=xy.map(p=>p.join(',')).join(' '),area=`25,225 ${coords} 675,225`;svg.innerHTML+=`<polygon points="${area}" fill="url(#fill)"/><polyline points="${coords}" fill="none" stroke="${value>=0?'#49d49d':'#fb7185'}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${value>=0?'#49d49d':'#fb7185'}" stop-opacity=".28"/><stop offset="1" stop-color="${value>=0?'#49d49d':'#fb7185'}" stop-opacity="0"/></linearGradient></defs>`;$('#curveReturn').textContent=`${value>=0?'+':''}${money(value)} all time`;$('#curveReturn').className=`pill ${value>=0?'positive':'negative'}`}
function renderTags(){const box=$('#tagBreakdown'),map={};trades.forEach(t=>t.tags.forEach(tag=>{map[tag]=(map[tag]||0)+pnl(t)}));const entries=Object.entries(map).sort((a,b)=>b[1]-a[1]);if(!entries.length){box.className='breakdown empty-state';box.textContent='Add tags to trades to discover what works.';return}const max=Math.max(...entries.map(x=>Math.abs(x[1])),1);box.className='breakdown';box.innerHTML=entries.slice(0,5).map(([tag,val])=>`<div class="breakdown-row"><span>#${escapeHtml(tag)}</span><div class="bar"><i style="width:${Math.abs(val)/max*100}%;background:${val>=0?'var(--green)':'var(--red)'}"></i></div><strong class="${val>=0?'positive':'negative'}">${signed(val)}</strong></div>`).join('')}
function renderRecent(){const box=$('#recentTrades');if(!trades.length){box.className='recent-trades empty-state';box.textContent='Nothing here yet. Every great system starts with one trade.';return}box.className='recent-trades';box.innerHTML=[...trades].sort((a,b)=>new Date(b.exitDate)-new Date(a.exitDate)).slice(0,4).map(t=>`<div class="recent-row"><div><b>${escapeHtml(t.symbol)}</b> <span>· ${dateFmt(t.exitDate)} · ${hold(t)}</span></div><strong class="${pnl(t)>=0?'positive':'negative'}">${signed(pnl(t))}</strong></div>`).join('')}
function renderTable(){const q=$('#searchTrades').value.toLowerCase(),tag=$('#tagFilter').value,side=$('#sideFilter').value;const tags=[...new Set(trades.flatMap(t=>t.tags))].sort();$('#tagFilter').innerHTML='<option value="">All tags</option>'+tags.map(x=>`<option value="${escapeAttr(x)}">#${escapeHtml(x)}</option>`).join('');$('#tagFilter').value=tag;let list=trades.filter(t=>(!q||[t.symbol,...t.tags,t.reason,t.lesson].join(' ').toLowerCase().includes(q))&&(!tag||t.tags.includes(tag))&&(!side||t.side===side));list.sort((a,b)=>{let av=sort.key==='pnl'?pnl(a):a[sort.key],bv=sort.key==='pnl'?pnl(b):b[sort.key];if(sort.key==='date'){av=new Date(a.exitDate);bv=new Date(b.exitDate)}return(av>bv?1:av<bv?-1:0)*sort.dir});$('#tradeTableBody').innerHTML=list.map(t=>`<tr><td>${dateFmt(t.exitDate)}</td><td><strong>${escapeHtml(t.symbol)}</strong></td><td><span class="side ${t.side}">${t.side.toUpperCase()}</span></td><td>${money(t.entryPrice)} <span style="color:var(--dim)">/</span> ${money(t.exitPrice)}</td><td>${t.quantity}</td><td class="${pnl(t)>=0?'positive':'negative'}"><strong>${signed(pnl(t))}</strong><br><small>${pnlPct(t).toFixed(2)}%</small></td><td><div class="tags">${t.tags.map(x=>`<span class="tag">#${escapeHtml(x)}</span>`).join('')}</div></td><td><button class="delete-btn" title="Delete trade" data-delete="${t.id}">×</button></td></tr>`).join('');$('#tableEmpty').style.display=list.length?'none':'block'}
function renderJournal(){const noted=trades.filter(t=>t.reason||t.lesson).sort((a,b)=>new Date(b.exitDate)-new Date(a.exitDate));$('#journalCards').innerHTML=noted.map(t=>`<article class="panel journal-card"><div class="journal-card-head"><div><h3>${escapeHtml(t.symbol)} <span class="side ${t.side}">${t.side.toUpperCase()}</span></h3><small>${dateFmt(t.exitDate)} · <b class="${pnl(t)>=0?'positive':'negative'}">${signed(pnl(t))}</b></small></div><div class="tags">${t.tags.map(x=>`<span class="tag">#${escapeHtml(x)}</span>`).join('')}</div></div>${t.reason?`<div class="note-section"><label>WHY I TOOK IT</label><p>${escapeHtml(t.reason)}</p></div>`:''}${t.lesson?`<div class="note-section"><label>WHAT I LEARNED</label><p>${escapeHtml(t.lesson)}</p></div>`:''}</article>`).join('');$('#journalEmpty').style.display=noted.length?'none':'block'}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escapeAttr(s=''){return escapeHtml(s)}
function render(){updateDashboard();renderTable();renderJournal()}
function openModal(){const f=$('#tradeForm');f.reset();const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());const now=d.toISOString().slice(0,16);f.entryDate.value=now;f.exitDate.value=now;$('#previewPnl').textContent='₹0.00';$('#previewPct').textContent='0.00%';$('#tradeModal').classList.add('open');$('#tradeModal').setAttribute('aria-hidden','false');f.symbol.focus()}
function closeModal(){$('#tradeModal').classList.remove('open');$('#tradeModal').setAttribute('aria-hidden','true')}
function showToast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
$('#openTradeModal').onclick=openModal;$$('[data-open-trade]').forEach(b=>b.onclick=openModal);$('#closeModal').onclick=closeModal;$('#cancelTrade').onclick=closeModal;$('#tradeModal').onclick=e=>{if(e.target===$('#tradeModal'))closeModal()};
$('#tradeForm').oninput=()=>{const f=new FormData($('#tradeForm')),entry=+f.get('entryPrice')||0,exit=+f.get('exitPrice')||0,qty=+f.get('quantity')||0,v=(f.get('side')==='long'?exit-entry:entry-exit)*qty;$('#previewPnl').textContent=signed(v);$('#previewPnl').className=v>0?'positive':v<0?'negative':'';$('#previewPct').textContent=entry?`${(v/(entry*qty)*100).toFixed(2)}%`:'0.00%'};
$('#tradeForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),trade={id:crypto.randomUUID(),symbol:f.get('symbol').trim().toUpperCase(),side:f.get('side'),entryPrice:+f.get('entryPrice'),exitPrice:+f.get('exitPrice'),quantity:+f.get('quantity'),entryDate:f.get('entryDate'),exitDate:f.get('exitDate'),tags:f.get('tags').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i),reason:f.get('reason').trim(),lesson:f.get('lesson').trim()};if(new Date(trade.exitDate)<new Date(trade.entryDate)){showToast('Exit time must be after entry time.');return}trades.push(trade);persist();closeModal();render();showToast(`${trade.symbol} saved to your journal.`)};
['searchTrades','tagFilter','sideFilter'].forEach(id=>$('#'+id).oninput=renderTable);$('#tradeTableBody').onclick=e=>{const id=e.target.dataset.delete;if(id&&confirm('Delete this trade?')){trades=trades.filter(t=>t.id!==id);persist();render();showToast('Trade deleted.')}};$$('th[data-sort]').forEach(th=>th.onclick=()=>{const key=th.dataset.sort;sort={key,dir:sort.key===key&&sort.dir==='desc'?'asc':'desc'};renderTable()});$$('.nav-link').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-view-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewJump));
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const names={dashboard:['TRADING PERFORMANCE','Good morning, trader.'],trades:['YOUR RECORD','All trades, all lessons.'],journal:['REFLECTIONS','Your trading memory.']};$('#pageEyebrow').textContent=names[id][0];$('#pageTitle').textContent=names[id][1];window.scrollTo({top:0,behavior:'smooth'})}
$('#exportCsv').onclick=()=>{if(!trades.length){showToast('Nothing to export yet.');return}const rows=[['Symbol','Side','Entry price','Exit price','Quantity','Entry date','Exit date','P&L','P&L %','Holding duration','Tags','Why I took it','What I learned'],...trades.map(t=>[t.symbol,t.side,t.entryPrice,t.exitPrice,t.quantity,t.entryDate,t.exitDate,pnl(t),pnlPct(t).toFixed(2),hold(t),t.tags.join(', '),t.reason,t.lesson])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ledgerly-trades.csv';a.click();URL.revokeObjectURL(a.href)};
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
$('#importCsv').onclick=()=>$('#importCsvFile').click();$('#importCsvFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const rows=parseCsv(await file.text());if(rows.length<2)throw new Error('No trade rows found');const head=rows.shift().map(x=>x.trim().toLowerCase()),col=name=>head.indexOf(name);const required=['symbol','side','entry price','exit price','quantity','entry date','exit date'];if(required.some(x=>col(x)<0))throw new Error('Use the Ledgerly export columns');const incoming=rows.map(r=>({id:crypto.randomUUID(),symbol:(r[col('symbol')]||'').trim().toUpperCase(),side:(r[col('side')]||'').trim().toLowerCase(),entryPrice:+r[col('entry price')],exitPrice:+r[col('exit price')],quantity:+r[col('quantity')],entryDate:r[col('entry date')],exitDate:r[col('exit date')],tags:(r[col('tags')]||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),reason:col('why i took it')>=0?r[col('why i took it')].trim():'',lesson:col('what i learned')>=0?r[col('what i learned')].trim():''})).filter(t=>t.symbol&&['long','short'].includes(t.side)&&t.entryPrice>0&&t.exitPrice>0&&t.quantity>0&&t.entryDate&&t.exitDate);if(!incoming.length)throw new Error('No valid trades found');trades.push(...incoming);persist();render();showToast(`${incoming.length} trade${incoming.length===1?'':'s'} imported.`)}catch(err){showToast(err.message)}finally{e.target.value=''}};
render();
